eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8003/eureka/
      
---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: azhar
aadhaarnos: 123456789012,745865891452,325612548547,256385471254
aadhaar:
  aadhaarno: 835113472986
  firstName: Azhar
  lastName: Shaikh
  middleName: Ashraf
  mobile: This has been removed since Aadhaar 2.1
  email: This has been removed since Aadhaar 2.1
  gender: Male
  dateofbirth: 23/12/1992
  careof: Ashraf Shaikh
  building: Parcel Depot Grant Road
  landmark: Grant Road Station
  street: Ali Bhai Premji Marg
  locality: Grant Road
  poname: Grant Road
  villagetowncity: Mumbai
  subdist: Mumbai
  dist: Mumbai
  state: Maharashtra
  pincode: 400007
  status: Success