server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8003/eureka/
management: 
      endpoints: 
        web: 
          exposure: 
            include: 'hystrix.stream'
      
      